language: c
compiler: gcc
install: true
dist: trusty
sudo: required
script:
  - make && sudo make install
  - make -C test test-likwidAPI
  - test/test-likwidAPI
  - /usr/local/bin/likwid-topology -c -C -g
  - /usr/local/bin/likwid-pin -p
  - sudo modprobe msr
  - make -C test streamGCC
  - /usr/local/bin/likwid-perfctr -i
  - /usr/local/bin/likwid-perfctr -C 0,1 -g L3 test/streamGCC
  - /usr/local/bin/likwid-perfctr -C 0,1 -g L3 -m test/streamGCC
  - /usr/local/bin/likwid-bench -t copy -w N:100MB:2
